# Generated by Django 5.0.3 on 2024-05-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=30)),
                ('image', models.ImageField(default=False, upload_to='upload')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
