# Generated by Django 5.0.3 on 2024-06-07 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSkill', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
