# Generated by Django 5.0.3 on 2024-06-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProject', '0004_alter_projectreview_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technologies_used',
            field=models.TextField(max_length=150),
        ),
    ]
