# Generated by Django 5.0 on 2024-03-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0009_alter_projectreview_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectreview',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
