# Generated by Django 5.0 on 2024-03-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0011_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=True, upload_to='upload'),
        ),
    ]
